require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.autocommands"
require "user.colorscheme"
require "user.cmp"
require "user.telescope"
require "user.harpoon"
require "user.treesitter"
require "user.treesitter-context"
require "user.autopairs"
require "user.comment"
require "user.gitsigns"
require "user.git-blame"
require "user.nvim-tree"
require "user.bufferline"
require "user.lualine"
require "user.toggleterm"
require "user.project"
require "user.impatient"
require "user.illuminate"
require "user.indentline"
-- require "user.alpha"
require "user.lsp"
require "user.notify"
require "user.functions"
-- require "user.whichkey"
require "user.fidget"
require "user.surround"
require "user.todo-comments"
-- require "user.winbar"
-- require "user.navic"
require "user.nvim-webdev-icons"
require "user.colorizer"
