-- https://github.com/microsoft/vscode/blob/main/src/vs/base/common/codicons.ts
-- go to the above and then enter <c-v>u<unicode> and the symbold should appear
-- or go here and upload the font file: https://mathew-kurian.github.io/CharacterMap/
-- find more here: https://www.nerdfonts.com/cheat-sheet
return {
    kind = {
        Array = "",
        Boolean = "",
        Class = "",
        Color = "",
        Constant = "",
        Constructor = "",
        Enum = "",
        EnumMember = "",
        Event = "",
        Field = "",
        File = "",
        Folder = "",
        Function = "",
        Interface = "",
        Keyword = "",
        Method = "",
        Module = "",
        Number = "",
        Object = "",
        Operator = "",
        Property = "",
        Reference = "",
        Snippet = "",
        String = "",
        Struct = "",
        Text = "",
        TypeParameter = "",
        Unit = "",
        Value = "",
        Variable = "",
    },
    git = {
        added = "",
        branch = "",
        modified = "",
        removed = "",
        Octoface = "",
    },
    diagnostics = {
        Error = "",
        Hint = "󰌵",
        Information = "",
        Question = "",
        Warning = "",
    },
    misc = {
        Robot = "󰚩",
        Tag = "",
        Telescope = "",
        Spaces = "󰞔",
    },
}
